### ISSUE TITLE
Course Tools and Blocks not Displaying

### ISSUE THREAD

**Issue by jinobi** [moodlerooms/moodle-theme_snap#10] opened 2015-07-17 10:26 UTC
Hi, In my installation, the course tools and blocks are displayed when Editing is off. When you turn on the Editing mode, it is displayed  as usual. In debug mode, there is a message Capability  "enrol/accesskey:manage" was not found!

**Comment by davidscotson** [comment] 2015-07-17 15:15
Closing as duplicate of #3, which is fixed and in the process of being released.

**Closed by davidscotson** 2015-07-17 15:15 UTC
