### ISSUE TITLE
Indentation of tree in admin menu

### ISSUE THREAD

**Issue by ecraven** [moodlerooms/moodle-theme_snap#31] opened 2016-05-25 06:07 UTC
As seen in the screenshot, the indentation for sub-levels in the settings tree is probably too much (especially the padding).
![admin-theme](https://cloud.githubusercontent.com/assets/215510/15529710/873575f6-224f-11e6-9159-0b919add062a.jpg)
Might I suggest adding something like the following
````
.block_settings .block_tree ul {
  margin-left: 8px;
  padding-left: 8px;
}
````
in order to get a less indentation (and a more readable view).

**Comment by davidscotson** [comment] 2016-05-25 10:17
It doesn't look like that for me. I wonder what the difference is?

The current setting for me when I inspect via the browser is:
```
.block_settings .block_tree li ul {
    padding-left: 8px;
    margin-left: 8px;
}
```
which isn't far from your total of 16px (margin + padding), though it only targets the child ul's.

Do you have any custom CSS that might be affecting ul tags?

**Comment by davidscotson** [comment] 2016-05-25 10:18
![screen shot 2016-05-25 at 11 18 10](https://cloud.githubusercontent.com/assets/7288187/15536696/67df99b4-226a-11e6-8990-96b7c9740833.png)

**Comment by stuartlamour** [comment] 2016-06-15 20:26
hi @ecraven 

apologies we cannot replicate the way this looks on your screenshot - can you use something like inspect in chrome to show the css making these look different from the standard version?

cheers
stuart

**Comment by ecraven** [comment] 2016-06-16 10:33
Hey Stuart! Sorry for taking so long to respond. That wash a fresh moodle install, so it should be reproducible. I have since changed a lot of things on it, but I will try to get a new setup going within a few days, then I'll paste all the relevant data.

Thanks for your patience!

**Comment by stuartlamour** [comment] 2016-07-07 15:51
Hi @ecraven,

we just pushed snap 3.0. Again, i'm unable to reproduce this in a moodle 3.0 build and snap 3.0 so please let us know if you are still experiencing this or we can close the issue.

Thanks
Stuart

**Closed** 2016-08-11 19:53 UTC
